### ISSUE TITLE
训练

### ISSUE THREAD

**Issue by zjp99** [xuannianz/FSAF#1]
您好，有些问题请教！制作voc数据集生成，csv文件。python train.py csv  VOC2007/annotations.csv  VOC2007/classes.csv
使用这个命令运行，提示"ImportError: No module named 'pycocotools'"，但是我使用的csv格式，使用RetinaNet训练没有报错，还有您的这个和RetinaNet一样也需要转换模型吗？

**Comment by xuannianz** [comment]
RetinaNet 的 CocoEval 这个 callback 是单独放到一个文件中的，它会判断数据集是否是 coco，如果是 coco 才会导入这个 callback. 我这里是把所有的 callbacks 都合并在一个文件，所以即使指定数据集类型为 csv，也会导入 CocoEval.
可以转换，也可以这样
https://github.com/xuannianz/FSAF/blob/f9164f865ca28b15a1ca25cf876090772cabba96/inference.py#L40-L44

**Comment by zjp99** [comment]
PS D:\Downloads\FSAF-master\FSAF-master> python train.py  csv D:/Downloads/FSAF-master/FSAF-master/datasets/VOC2007/annotations.csv D:/Downloads/FSAF-master/FSAF-master/datasets/VOC2007/classes.csv
Using TensorFlow backend.
Traceback (most recent call last):
  File "train.py", line 27, in <module>
    from callbacks import RedirectModel
  File "D:\Downloads\FSAF-master\FSAF-master\callbacks.py", line 3, in <module>
    from utils.coco_eval import evaluate_coco
  File "D:\Downloads\FSAF-master\FSAF-master\utils\coco_eval.py", line 17, in <module>
    from pycocotools.cocoeval import COCOeval
ModuleNotFoundError: No module named 'pycocotools'
----------------------------------------------------------------------
以上是我的错误我的voc2007结构/annotations+ImageSets+JPEGImages+annotations.csv+classes.csv
train之后报错

**Comment by xuannianz** [comment]
`pip install git+https://github.com/cocodataset/cocoapi.git#subdirectory=PythonAPI` 安装一下 pycocotools 这个包 或者 注释掉 https://github.com/xuannianz/FSAF/blob/f9164f865ca28b15a1ca25cf876090772cabba96/callbacks.py#L3

**Comment by zjp99** [comment]
可能是数据格式问题，我使用csv，Epoch 1/50
Traceback (most recent call last):
  File "train.py", line 491, in <module>
    main()
  File "train.py", line 486, in main
    validation_data=validation_generator
  File "F:\software\Anaconda3\lib\site-packages\keras\legacy\interfaces.py", line 91, in wrapper
    return func(*args, **kwargs)
  File "F:\software\Anaconda3\lib\site-packages\keras\engine\training.py", line 1732, in fit_generator
    initial_epoch=initial_epoch)
  File "F:\software\Anaconda3\lib\site-packages\keras\engine\training_generator.py", line 220, in fit_generator
    reset_metrics=False)
  File "F:\software\Anaconda3\lib\site-packages\keras\engine\training.py", line 1514, in train_on_batch
    outputs = self.train_function(ins)
  File "F:\software\Anaconda3\lib\site-packages\tensorflow\python\keras\backend.py", line 3292, in __call__
    run_metadata=self.run_metadata)
  File "F:\software\Anaconda3\lib\site-packages\tensorflow\python\client\session.py", line 1458, in __call__
    run_metadata_ptr)
tensorflow.python.framework.errors_impl.InternalError: Unsupported feed type
-----------------------------------------------------------------------------------------
您能将您的实验数据发我一份吗？VOC的。想复现下实验，然后学习。

**Comment by zjp99** [comment]
首先很不好意思再次打扰您，本人刚入门，有些问题，VOC07(测试4952，训练2501+验证2510)VOC2017(测试5138，训练5717+验证5823)
VOC2012 trainval.txt + Pascal VOC2012 train.txt, ------There are 14014 images for training
and validated on Pascal VOC2007 val.txt. ------and 2510 images for validation.
想知道14014是如何来的？

------------------ 原始邮件 ------------------
发件人: "xuannianz"<notifications@github.com>;
发送时间: 2019年10月11日(星期五) 下午4:47
收件人: "xuannianz/FSAF"<FSAF@noreply.github.com>;
抄送: "🌚🌚52Hz的老赵"<3238816982@qq.com>;"Author"<author@noreply.github.com>;
主题: Re: [xuannianz/FSAF] 训练 (#1)




VOC 你可以按照 README 里面提到的方式生成，没有什么特别的改动。

**Comment by xuannianz** [comment]
我写错了，5717 + 5823 + 2501 = 14041

**Comment by yuanhanxiagn** [comment]
![image](https://user-images.githubusercontent.com/39044405/67930034-cca05980-fbf9-11e9-8ae4-efc9ca1457f5.png)
你好，麻烦请教一下，我是按照
![image](https://user-images.githubusercontent.com/39044405/67930074-ec378200-fbf9-11e9-9ac3-a832c42097d2.png)
写的为什么出现这个问题啊

**Comment by xuannianz** [comment]
你好，试试调试一下 train_generator 和 val_generator 的 __getitem__() 方法，看看返回结果对不对
