### ISSUE TITLE
添加一个分支后，出现一个操作缺少梯度的报错。

### ISSUE THREAD

**Issue by kuang-linyi** [xuannianz/FSAF#10]
作者，您好。
      感谢您在编写FSAF代码的贡献。我目前在尝试原始您的FSAF代码上，加一个与分类层并行的分支，并针对这个分支上添加一个损失。当我写完这个结构，运行时出现了以下报错，报错显示某个操作缺少梯度，一直找不到解决思路。作者是否在编程中遇到这个错误，希望作者能给予点拨。
   谢谢您。
ValueError: An operation has `None` for gradient. Please make sure that all of your ops have a gradient defined (i.e. are differentiable). Common ops without gradient: K.argmax, K.round, K.eval.

**Comment by xuannianz** [comment]
没遇到过，你检查一下 loss 函数是否可导

**Comment by kuang-linyi** [comment]
作者，您好，还是上次在原来的FSAF上添加一个分支与损失的问题，上次梯度为NONE的问题已经解决。但我又遇到这个报错，实在找不到问题的缘由，希望你能给予点拨，谢谢您。
tensorflow.python.framework.errors_impl.InvalidArgumentError: ConcatOp : Ranks of all input tensors should match: shape[0] = [21175,1] vs. shape[1] = [273]
	 [[Node: fsaf_target/map/while/concat_23 = ConcatV2[N=2, T=DT_FLOAT, Tidx=DT_INT32, _device="/job:localhost/replica:0/task:0/device:GPU:0"](fsaf_target/map/while/concat_17, fsaf_target/map/while/cond_3/Merge_5, fsaf_target/map/while/concat_4/axis)]]
	 [[Node: fsaf_target/map/while/cond_3/Cast_11/_2806 = _Send[T=DT_INT32, client_terminated=false, recv_device="/job:localhost/replica:0/task:0/device:GPU:0", send_device="/job:localhost/replica:0/task:0/device:CPU:0", send_device_incarnation=1, tensor_name="edge_6392_fsaf_target/map/while/cond_3/Cast_11", _device="/job:localhost/replica:0/task:0/device:CPU:0"](fsaf_target/map/while/cond_3/Cast_11)]]

**Comment by kuang-linyi** [comment]
您好，问题已经解决。
