### ISSUE TITLE
请问您输入网络的input_size是多少？

### ISSUE THREAD

**Issue by freedom521jin** [xuannianz/FSAF#13]

**Comment by xuannianz** [comment]
Retinanet 是最小边 800，最大边 1000. Yolo 是 416.

**Comment by freedom521jin** [comment]
> Retinanet 是最小边 800，最大边 1000. Yolo 是 416.

好的多谢

**Comment by freedom521jin** [comment]
您好，我在训练自己数据的时候，出现这样的错误：
[W ./tensorflow/core/grappler/optimizers/graph_optimizer_stage.h:241 ] Failed to run optimizer ArithmeticOptimizer, stage RemoveStackStrideSliceSameAxis node level_select/map/while/map_4/while/strided_slice_13. Error:ValidateStridedSliceOp return partial shapes [?,1] ans [?].
但是可以正常训练，我的环境是CUDA10.0，tensorflow1.13.1，keras2.2.5。
训练命令：python3 --weights ResNet-50-model.keras.h5 --backbone resnet50 --gpu 0 --random-transform pascal VOC2007
楼主有遇到过这样的问题吗？

**Comment by xuannianz** [comment]
遇到过，升级 tf 到 1.14.0 试试. https://github.com/matterport/Mask_RCNN/issues/1264
