### ISSUE TITLE
怎样训练自己的数据集？

### ISSUE THREAD

**Issue by henbucuoshanghai** [xuannianz/FSAF#16]

**Comment by xuannianz** [comment]
根据你的 annotations 的格式(csv, pascal, coco)，在运行 train.py 时指定。

**Comment by henbucuoshanghai** [comment]
大佬FSAF论文有一些不懂，请问博客解读？


fsaf层同样分类回归，不懂为什么？原始的anchor不用了？

**Comment by xuannianz** [comment]
知乎上有不少博文解读的很详细，比如 https://zhuanlan.zhihu.com/p/58508985
fsaf 是 anchor-free 的, anchor-based 的 detector 一般是计算 anchor 和 gt box 的 iou, 选择合适的 anchor 所在的 feature map 来提取特征，而 fsaf 是 online 提取特征的

**Comment by henbucuoshanghai** [comment]
&nbsp;fsaf 是 online 提取特征的然后特征用于什么？fsaf和原始anchor based有什么关系呢？
