### ISSUE TITLE
尊敬的博主，请问为什么训练过程中选择prediction_model去测试验证集

### ISSUE THREAD

**Issue by KingPengcj** [xuannianz/FSAF#17]

**Comment by xuannianz** [comment]
没太懂啊， validation 就是监测你的训练的模型的推理能力如何

**Comment by KingPengcj** [comment]
看到了这段代码，所以才有点迷惑，以往接触的网络都是计算val_loss，此处用prediction_model进行验证，有点不太懂，还请博主指点迷津
def create_callbacks(training_model, prediction_model, validation_generator, args):
    """
    Creates the callbacks to use during training.

    Args
        training_model: The model that is used for training.
        prediction_model: The model that should be used for validation.
        validation_generator: The generator for creating validation data.
        args: parseargs args object.

    Returns:
        A list of callbacks used for training.
    """

**Comment by xuannianz** [comment]
计算 mAP 要比 val loss 更直观

**Comment by KingPengcj** [comment]
好的，谢谢您啦
