### ISSUE TITLE
yolo_FSAF模块检测结果问题

### ISSUE THREAD

**Issue by KingPengcj** [xuannianz/FSAF#18]
尊敬的博主，您好，在您的代码里，对于yolo_FSAF模块，最终的测试结果，总是有300个，这是为什么，有什么办法可以把无用的结果剔除吗？

**Comment by xuannianz** [comment]
这个是为了做 batch inference。 如果只想测试一张的话，可以把这部分填充到 300 个 detections 的代码去掉。
