### ISSUE TITLE
加载预训练模型主干的问题

### ISSUE THREAD

**Issue by kuang-linyi** [xuannianz/FSAF#2]
尊敬的项目作者，您好。我看到您的代码后，有以下疑问，希望能得到您的解答。
在您写的train,py中,有weights = backbone.download_imagenet()这条语句，请问若按照您在GitHub关于train的提示进行操作，程序能否执行这条语句，假设执行这条语句后，是否能够执行从网上下载了预训练resnet50主干的操作？

**Comment by xuannianz** [comment]
你好，会下载的，你执行一下就可以看出来了。
