### ISSUE TITLE
pretrained weights

### ISSUE THREAD

**Issue by Gao-Huashuai** [xuannianz/FSAF#24]
Hi, author! If I want use the pretrained model to train my own datas, what should I do? I used your publiced pretrained weights to initial the network when using my own datas, but there was an error(class dimension was inconsistency in  fsaf layer). If I use the pretrained weights about resnet101 which is downloaded in keras-retinanet, it is okey?

**Comment by xuannianz** [comment]
Hi @Gao-Huashuai ,make sure you have set correct number of classes here. https://github.com/xuannianz/FSAF/blob/fe43ac76f9d2a86d84ff41cc20d764fded39b839/train.py#L441
