### ISSUE TITLE
lower map results

### ISSUE THREAD

**Issue by hustliujian** [xuannianz/FSAF#27]
Hi, 

I prepared dataset like you said and trained the network with resent50 backbone, 
but my mAP result on VOC2007 test is nearly 0.5, is there any differenct between 
latest code and the version generating your result ? or can you give me any idea where 
I am wrong maybe ?

**Comment by xuannianz** [comment]
Hi @hustliujian, I have not updated any code after upload the trained model. What is your init lr?

**Comment by hustliujian** [comment]
My init lr is 1e-4. And I increase the batch-size to 4, 8, the mAP increased to 0.6, so maybe it's the problem about batch-size, should I go on increasing it  ?
