### ISSUE TITLE
Try to train on my own dataset?

### ISSUE THREAD

**Issue by cuiziteng** [xuannianz/FSAF#28]
If I want train on my own set,should I set the CSV file as follow, just same as the retinanet you use?
 /data/imgs/img_001.jpg,837,346,981,456,cow
/data/imgs/img_002.jpg,215,312,279,391,cat
/data/imgs/img_002.jpg,22,5,89,84,bird
/data/imgs/img_003.jpg,,,,,

**Comment by xuannianz** [comment]
Hi @keersujiade , yes. If you encounter any problem, just post here.
