### ISSUE TITLE
FSAF loss实现的疑问

### ISSUE THREAD

**Issue by Jialeen** [xuannianz/FSAF#3]
尊敬的项目作者，您好。我在看您的这个项目代码后，有个疑问：FSAF模块论文里把特征图分为effective, ignoring, negative三部分，代码中我没有找到这样的划分，您可以给我讲下是在哪实现的吗？
非常感谢！

**Comment by xuannianz** [comment]
你好，你看下这一部分
https://github.com/xuannianz/FSAF/blob/3e6177b013bab87f21e43cc84ae983d8135c7028/fsaf_layers.py#L169-L192
