### ISSUE TITLE
Map评估方式的疑问

### ISSUE THREAD

**Issue by kuang-linyi** [xuannianz/FSAF#4]
请问作者，您这个项目所采用的map评估方式是VOC2010以前的方法（利用P-R曲线上11个坐标点计算），还是VOC2010及以后的方式？

**Comment by xuannianz** [comment]
你好，是后一种方式，可以看一下具体的实现
https://github.com/xuannianz/FSAF/blob/3e6177b013bab87f21e43cc84ae983d8135c7028/utils/eval.py#L30-L59
