### ISSUE TITLE
您好，关于FSAF Target层的疑问

### ISSUE THREAD

**Issue by cgd306948366** [xuannianz/FSAF#5]
fsaf_layers.py，第224行
`level_min_area_box_indices = tf.argmin(level_area, axis=0, output_type=tf.int32)`
我理解的是这里的操作是对于某一层的 select boxes，来设定其target。如果多个boxes重叠则取最大值，这里为什么取最小值的idx呢？

**Comment by xuannianz** [comment]
论文 Section 3.1 有这么一段 "Note that if the effective boxes of two instances overlap in one level, the smaller instance has higher priority."
