### ISSUE TITLE
关于FSAF中anchor-based分支的疑问

### ISSUE THREAD

**Issue by kuang-linyi** [xuannianz/FSAF#6]
请问作者，您的代码中是否包含了论文中提到的anchor-based分支？我看了您的代码中，没有看到anchor-based分支结构。
期待您的回复，谢谢。

**Comment by xuannianz** [comment]
你好，anchor-based 部分就是原来 keras-retinanet 那部分。现在 anchor-based 和 anchor-free 没整合在一起，只会训练 anchor-free 部分。
https://github.com/xuannianz/FSAF/blob/3e6177b013bab87f21e43cc84ae983d8135c7028/models/retinanet.py#L382-L501
