### ISSUE TITLE
关于VOOC数据集测试时的细节

### ISSUE THREAD

**Issue by ZY-Russell** [xuannianz/FSAF#7]
您好！非常感谢您的工作！
  我想知道，您在README中给出的mAP是IOU=0.5时得出的吗？您在测试时使用了什么数据增强方法？您的特定服务器配置下运行FSAF的FPS大致是多少呢？期待您的回复，非常感谢！！！

**Comment by xuannianz** [comment]
你好,
是的, mAP<sub>50</sub>. 
增强方法主要是形变和颜色变化。
FPS 我还没有统计过。在 2080ti 下跑，backbone=resnet101, min_side=800，max_side=1333 的情况下我测试 VOC2007 的图片大部分在 80 多 ms。
