### ISSUE TITLE
关于COCO数据集的测试情况

### ISSUE THREAD

**Issue by kuang-linyi** [xuannianz/FSAF#9]
作者，您好。请问您的这个代码能不能测试COCO数据集？
还有，如果您之前用过COCO跑过程序，这个代码的结果和论文的实验结果相差大吗？
期待您的回复，谢谢。

**Comment by xuannianz** [comment]
你好，代码是可以测试 coco 的。但是数据集太大，我这边资源有限，还没有跑过。
等有时间跑一跑，把结果贴出来。
